platform :ios, '15.0'

def shared_pods
  use_frameworks!
  
  pod 'SnapKit'
  pod 'HandyText', :git => 'https://github.com/mmrmmlrr/HandyText', :branch => 'feature/v2'
  pod 'Toast-Swift'
  pod 'NVActivityIndicatorView'
  pod 'SDWebImage', '~> 5.0'
  pod 'ReachabilitySwift'
  # ^ is toolbox pods
  pod 'SwiftyReceiptValidator'
  pod 'TPInAppReceipt' # for in-app receipt validation
  pod 'RealmSwift', '~>10'
end

target 'oxbridge-baby-ios' do
  shared_pods
end
